// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc_db

import (
	"time"
)

type Paste struct {
	Shortlink                 string
	ExpirationLengthInMinutes int32
	CreatedAt                 time.Time
	PastePath                 string
}
